best_parameters:
  batch_size: 32
  dropout_rate: 0.15990213464750794
  epochs: 158
  gate_threshold: 0.6140703845572054
  guide_loss_weight: 1.4159046082342293
  guided_attention_enabled: false
  learning_rate: 0.0005106823667399512
  p_attention_dropout: 0.0912139968434072
  postnet_dropout_rate: 0.10284688768272232
  warmup_steps: 2030
best_value: 0.4856733814345504
metadata:
  config_path: smart_tuner/config.yaml
  optimization_type: composite_tts_objective
  timestamp: '20250623_201104'
  tts_version: Smart Tuner V2 TTS
n_trials: 10
study_name: tacotron2_tts_20250623_194559
tts_analysis:
  best_value: 0.4856733814345504
  completed_trials: 10
  improvement_rate: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    IfvB2n0+jz8=
  mean_value: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    x8cOmcIh4D8=
  parameter_importance:
    batch_size: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      K9NXUphbpD8=
    dropout_rate: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      CVgkdLh3sz8=
    epochs: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      j+708dMMvj8=
    gate_threshold: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      TEFlbb7Gxz8=
    guide_loss_weight: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      591SI3ahvj8=
    guided_attention_enabled: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      xYO72yxjbz8=
    learning_rate: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      VpV+UV97yz8=
    p_attention_dropout: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      F7Kd9AoFpj8=
    postnet_dropout_rate: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      UTISSy+Ptz8=
    warmup_steps: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      OF1hoyebuz8=
  std_value: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    FTC7iVgIkj8=
  total_trials: 10
  tts_insights: []
  tts_recommendations:
  - Включение guided attention может улучшить качество alignment
  worst_value: 0.5378910251286668
