# 🚀 УЛУЧШЕННАЯ КОНФИГУРАЦИЯ SMART TUNER V2
# Исправлены все проблемы качества обучения

# 🧠 Adaptive Advisor - Более умные действия
adaptive_advisor:
  enabled: true
  evaluation_window: 50  # Уменьшено для быстрой реакции
  min_history_for_decision: 100  # Уменьшено для более ранних решений
  min_reward_threshold: -0.05  # Смягчено для лучшей адаптации
  
  # Улучшенная диагностика проблем
  diagnostics:
    instability:
      grad_norm_threshold: 100.0  # Снижено с 200 для раннего обнаружения
    overfitting:
      threshold: 3.0  # Снижено с 5.0 для лучшего контроля
      window_size: 30  # Уменьшено для быстрой реакции
    stagnation:
      min_delta: 0.001  # Увеличено с 0.0005 для стабильности
      window_size: 100  # Уменьшено для быстрой реакции
    attention_failure:
      min_alignment_score: 0.5  # Снижено с 0.7 для реалистичности
      alignment_window: 50  # Уменьшено
    gate_collapse:
      min_gate_accuracy: 0.6  # Снижено с 0.8 для реалистичности
      gate_window: 30  # Уменьшено

  # Более эффективные действия
  default_actions:
    instability:
      name: stability_boost
      params:
        learning_rate_multiplier: 0.8  # Более мягкое снижение
        gradient_clipping: 5.0
        batch_size_adjust: 0.8
    overfitting:
      name: regularization_boost
      params:
        dropout_increase: 0.05  # Мягкое увеличение
        weight_decay_increase: 0.1
    stagnation:
      name: learning_boost
      params:
        learning_rate_multiplier: 1.2  # Умеренное повышение
        warmup_steps_adjust: 1.1
    attention_failure:
      name: attention_recovery
      params:
        guided_attention_boost: 1.5
        attention_dropout_reduction: 0.05
    gate_collapse:
      name: gate_recovery
      params:
        gate_loss_weight: 1.3
        gate_threshold_adjust: -0.05

# 📊 Более реалистичные пороги качества TTS
training_safety:
  enabled: true
  max_training_hours: 24.0  # Уменьшено с 48
  min_training_hours: 2.0   # Увеличено с 8 (было слишком долго)
  max_validation_loss: 30.0  # Снижено с 50.0
  min_training_steps: 5000   # Снижено с 20000 для быстрых результатов
  
  # 🎯 ИСПРАВЛЕННЫЕ критерии качества TTS
  tts_quality_checks:
    # Более консервативные пороги для проверки качества
    min_attention_alignment: 0.6      # Повышено с 0.4 для более строгих требований
    min_gate_accuracy: 0.7           # Повышено с 0.5 
    max_validation_loss: 15.0        # Понижено с 25.0 для более строгих требований
    mel_quality_threshold: 0.4       # Повышено с 0.3
    min_training_progress: 0.08      # Повышено с 0.05 для обеспечения прогресса
    
    # Минимальные требования для досрочного завершения
    min_validation_steps: 5          # Минимум validation шагов
    min_training_time_minutes: 15    # Минимум времени обучения
    required_checks_percentage: 0.9  # 90% проверок должны пройти
    
    # Критические проверки (все должны пройти)
    critical_checks:
      - attention_alignment
      - gate_accuracy  
      - validation_loss

# 🔧 Оптимизированные гиперпараметры 
hyperparameter_search_space:
  batch_size:
    type: int
    min: 8
    max: 64
    default: 32
    
  epochs:
    type: int
    min: 500          # Минимум для базового качества
    max: 5000         # Максимум для предотвращения переобучения  
    default: 2000     # Оптимальное значение для большинства случаев
    
  learning_rate:
    type: float
    min: 0.000001     # 1e-6
    max: 0.001        # 1e-3
    default: 0.0001   # 1e-4 - Сбалансированное значение
    log: true         # Логарифмическая шкала для learning rate
    
  warmup_steps:
    type: int
    min: 500     # Уменьшено с 1000
    max: 3000    # Уменьшено с 5000
    default: 1500
    
  guided_attention_enabled:
    type: categorical
    choices: [true, false]
    default: true
    
  guide_loss_weight:
    type: float
    min: 0.5
    max: 3.0     # Уменьшено с 5.0
    default: 1.5 # Увеличено с 1.0
    
  p_attention_dropout:
    type: float
    min: 0.0
    max: 0.2     # Уменьшено с 0.3
    default: 0.1
    
  gate_threshold:
    type: float
    min: 0.3
    max: 0.7
    default: 0.5
    
  dropout_rate:
    type: float
    min: 0.1
    max: 0.4     # КРИТИЧЕСКИ ВАЖНО: уменьшено с 0.7
    default: 0.2 # Уменьшено с 0.3
    
  postnet_dropout_rate:
    type: float
    min: 0.0
    max: 0.2     # Уменьшено с 0.3
    default: 0.1

# 🎯 Улучшенная оптимизация
optimization:
  direction: minimize
  n_trials: 20  # Разумное количество
  objective_metric: composite_tts_score
  continue_training: true
  
  # Больше времени для каждого trial
  full_epochs_per_trial: 80  # Уменьшено с 100 для скорости
  overfitting_penalty: 0.03  # Уменьшено с 0.05
  
  # Более щадящие TTS настройки
  tts_specific:
    min_training_steps: 3000         # Снижено с 20000
    attention_convergence_threshold: 0.6  # Снижено с 0.8
    gate_accuracy_threshold: 0.65    # Снижено с 0.85
    early_pruning_disabled_epochs: 50 # Уменьшено с 100
    
  # Более сбалансированная композитная оценка
  composite_objective:
    weights:
      validation_loss: 0.5           # Увеличено с 0.4
      attention_alignment_score: 0.2 # Уменьшено с 0.3
      gate_accuracy: 0.2            # То же
      mel_quality_score: 0.1        # То же
    normalize_scores: true
    quality_bonus_threshold: 0.8     # Бонус за хорошее качество
    progress_weight: 0.1             # Вес прогресса обучения

# 🛑 Система раннего останова (обновлена для предотвращения преждевременной остановки)
early_stopping:
  enabled: true
  
  # Современные критерии останова
  patience_epochs: 200        # Увеличено для TTS
  min_delta: 0.001           # Минимальное улучшение
  monitor_metric: "val_loss"
  
  # Адаптивные пороги на основе фазы обучения
  adaptive_thresholds:
    enabled: true
    
    # Фаза выравнивания attention (0-500 эпох)
    alignment_phase:
      patience: 100
      min_improvement: 0.01
      attention_threshold: 0.5
      
    # Фаза обучения (500-2000 эпох)  
    learning_phase:
      patience: 150
      min_improvement: 0.005
      attention_threshold: 0.8
      
    # Фаза тонкой настройки (2000+ эпох)
    fine_tuning_phase:
      patience: 200
      min_improvement: 0.001
      attention_threshold: 0.9

# 📈 TTS метрики с реалистичными весами
tts_metrics:
  attention_metrics:
    alignment_score_weight: 1.0
    attention_entropy_weight: 0.3  # Уменьшено с 0.5
    attention_sharpness_weight: 0.2 # Уменьшено с 0.3
  gate_metrics:
    accuracy_weight: 1.0
    precision_weight: 0.6  # Уменьшено с 0.8
    recall_weight: 0.6     # Уменьшено с 0.8
  mel_metrics:
    spectral_distance_weight: 1.0
    mel_cepstral_distortion_weight: 0.5  # Уменьшено с 0.7

# 🎓 Фазовое обучение TTS
tts_phase_training:
  enabled: true
  phases:
    pre_alignment:
      max_epochs: 500
    alignment_learning:
      max_epochs: 1500
    fine_tuning:
      max_epochs: 3000

# 🔧 Системные настройки
experiment_name: tacotron2_smart_v2
output_dir: output
checkpoint_path: data/checkpoint
dataset_path: data/dataset
hparams_path: hparams.py

# 🔌 Порты сервисов
ports:
  mlflow: 5000
  tensorboard: 5001
  optimization_engine: 5002
  streamlit: 5003
  log_watcher: 5005
  metrics_store: 5006
  param_scheduler: 5007
  early_stop_controller: 5008
  alert_manager: 5009
  model_registry: 5010

# 📊 MLflow настройки
mlflow:
  tracking_uri: mlruns
  experiment_name: tacotron2_smart_optimization

# 🏆 Реестр моделей
model_registry:
  path: smart_tuner/models
  best_model_name: best_tts_model.pt
  max_models: 3  # Уменьшено с 5
  primary_metric: val_loss
  minimize_metric: true

# 🔄 Планировщик параметров
parameter_scheduling:
  learning_rate:
    enabled: true
    strategy: cosine
    start_value: 0.001
    end_value: 0.0001
    total_steps: 8000  # Уменьшено с 10000

parameter_scheduling_config:
  update_frequency: 20  # Увеличено с 10

# 🎯 Финальное обучение
final_training:
  epochs: 200

# 📝 Обучение
training:
  base_command: python train.py
  python_executable: python
  script_path: train.py
  continue_from_checkpoint: true
  full_training: true

# 🔐 Ресурсы
resources:
  checkpointing:
    path: output

# 📱 Telegram уведомления
telegram:
  enabled: true
  bot_token: 2010534305:AAHqgXYT5RPcLoJe-wNdFaFbIJvJsN2xUHA
  chat_id: '536955174'
  parse_mode: Markdown
  disable_web_page_preview: true
  notifications:
    training_start: true
    training_complete: true
    optimization_updates: true
    error_alerts: true
    early_stop: true
    metrics_summary: true 